server:
  port: 80

spring:
  application:
    name: cloud-hystrix-consumer-service



eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: consumerHy80

ribbon:
  #执行方法读取到结果的超时时间，默认一秒，单位为毫秒
  ReadTimeout: 5000
  #与提供者建立连接的超时时间
  ConnectTimeout: 5000

feign:
  hystrix:
    enabled: true