server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true    #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/select/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001          #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/timeOut/**         # 断言，路径相匹配的进行路由
            #- After=2020-02-21T15:51:37.485+08:00[Asia/Shanghai]
            #- After=2020-09-16T21:46:01.277+08:00[GMT+08:00]          #只允许在什么时间后才能进行访问，上述两种格式均可
            #- Before=2020-09-16T21:46:01.277+08:00[GMT+08:00]    #只允许在什么时间前进行访问
            #- Between=2020-09-16T21:46:01.277+08:00[GMT+08:00],2020-09-16T22:46:01.277+08:00[GMT+08:00] #只允许在什么时间段进行访问
            #- Host=**.zxq.com            #只允许**.zxq.com域名进行访问
            #- Method=GET                  #只允许get请求访问
            #- Cookie=username,zzyy      #必须带指定cookie才能访问
            #- Header=X-Request-Id, \d+  # 请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Query=baz                 #请求的参数中包含baz参数，这个不是很懂

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
