server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer8802
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      binders:
        defaultRabbit:
          type: rabbit   #默认绑定消息组件类型
      bindings:
        input:
          destination: studyExchange  #表示要使用的exchange的名称
          content-type: application/json  #设置消息返回的格式为json，文本设置为“text/plain”
          binder: defaultRabbit      #设置要绑定的具体消息设置,如果爆红也不影响
          group: zxqA              #设置分组，同组的消费者处于竞争关系，会轮询获得消息，不同组的会重复消费